services:
  - type: web
    name: onda-planification-api
    env: docker
    plan: free
    region: frankfurt # You can change this to your preferred region (e.g., oregon, ohio)
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
      # Remplace par l'URL exacte de ton frontend Vercel après déploiement
      - key: CORS_ALLOWED_ORIGINS
        value: https://ton-app.vercel.app